FROM apache/airflow:2.10.0-python3.11

USER root
COPY requirements.txt /tmp/requirements.txt
COPY requirements-airflow.txt /tmp/requirements-airflow.txt
RUN pip install --no-cache-dir -r /tmp/requirements-airflow.txt
USER airflow
